version: '3.9'

services:
  setup:
    build: ./setup/
    volumes:
      - .:/app
    command: bash /app/setup/download.sh
  sdxl: &base_sdxl
    build: ./sdxl/
    shm_size: '2gb'
    command: python ComfyUI/main.py --listen --port 8188
    volumes:
      - ./models/:/app/ComfyUI/models/
      - ./output/:/app/ComfyUI/output/
      - ./custom_nodes/:/app/ComfyUI/custom_nodes/
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  sdxl-legacy:
    <<: *base_sdxl
    profiles:
      - sdxl-legacy
    command: python ComfyUI/main.py --listen --port 8188 --disable-cuda-malloc
