version: '3.9'

services:
  setup:
    build: .
    dockerfile: Dockerfile.setup
    volumes:
      - .:/app
    command: /app/download.sh
  sdxl:
    build: .
    dockerfile: Dockerfile.sdxl
    command: python ComfyUI/main.py --listen --port 8188
    volumes:
      - .:/app
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
