version: '3.9'

services:
  setup:
    build: ./setup/
    profiles:
      - setup
    volumes:
      - .:/app
    command: bash /app/setup/download.sh
  sdxl: &base_sdxl
    build: ./sdxl/
    profiles:
      - sdxl
    command: python ComfyUI/main.py --listen --port 8188
    volumes:
      - ./models/:/app/ComfyUI/models/
      - ./output/:/app/ComfyUI/output/
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  sdxl-legacy:
    <<: *base_sdxl
    profiles:
      - sdxl-legacy
    command: python ComfyUI/main.py --listen --port 8188 --disable-cuda-malloc
  lora:
    build: ./lora/
    profiles:
      - lora
    volumes:
      - ./sd-scripts/:/app/sd-scripts/
      - ./lora/:/app/run/
      - ./models/:/app/models/
      - ./fine-tuned/:/app/fine-tuned/
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
